platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

def shared
  pod 'RxEureka', :path => '../'
end

def shared_tests
  pod 'Nimble'
  pod 'Quick', '~>  2.1'
end

target 'RxEureka-Example' do
  shared
end

target 'RxEureka-Tests' do
  shared
  shared_tests
end
